# a "service" which exposes the pod for exposing goserver and sends traffic
# to the pod
apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  # selector as defined in goserver pod definition
  selector:
    app: goserver
  # a node port exposes the given port such that it is accessible with
  # node's IP
  type: NodePort
  ports:
    - protocol: TCP
      # the port at which this service is exposed in-cluster
      port: 80
      # the port at which this service will listen for external traffic
      targetPort: 8080
